### ISSUE TITLE
It is not feasible for a react app created in typescript

### ISSUE THREAD

**Issue by zourdyzou** [itsrennyman/react-plock#17]
it will be good if we create a types package (small) and push it to the `DefinitelyTyped` repos

**Comment by zourdyzou** [comment]
anyway this is a great implementation of Masonry Layout

**Comment by itsrennyman** [comment]
Hello,

Currently taking care of a solution for your problem!

**Comment by itsrennyman** [comment]
Hi, just released a major version which is totally rewritten in TypeScript. In the library, there are also the types for the Plock props and the Breakpoint.

Please, check out a couple of little breaking changes in the API, and have a look at the [v2.0.0](https://github.com/itsrennyman/react-plock/releases/tag/v2.0.0) changelog!

Enjoy!
