### ISSUE TITLE
Build fails on Gatsby project - WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ramit-mitra** [itsrennyman/react-plock#18]
Hello,
I am using `react-plock` for a Gatsby project and it's causing the build to fail. 

**Definition in package.json**,
"react-plock": "^1.1.0",

**Error message**,
  WebpackError: ReferenceError: window is not defined

  - index.js:1
    [ramitmitra.com]/[react-plock]/dist/index.js:1:409

  - index.js:1
    [ramitmitra.com]/[react-plock]/dist/index.js:1:789

  - react.js:35
    [ramitmitra.com]/[fast-deep-equal]/react.js:35:32

  - useCallbackRef.js:28
    [ramitmitra.com]/[@restart]/hooks/esm/useCallbackRef.js:28:18

  - useEventCallback.js:6
    [ramitmitra.com]/[@restart]/hooks/esm/useEventCallback.js:6:1

  - static-entry.js:295
    webpack:/ramitmitra.com/.cache/static-entry.js:295:22

  - useMounted.js:2
    [ramitmitra.com]/[@restart]/hooks/esm/useMounted.js:2:1
    

Please look into the issue and release a fix. Thank you for the great package and all the hard work.

**Comment by ramit-mitra** [comment]
The issue occurs in versions `1.1.0` and `1.2.0`. Installing version `1.0.0` with `gatsby 4.14` does not cause this exception during the build.

**Comment by ramit-mitra** [comment]
Raised a PR to hopefully get it sorted, please review https://github.com/itsrennyman/react-plock/pull/19

**Comment by itsrennyman** [comment]
Hi, released.
