### ISSUE TITLE
typo in grid declaration

### ISSUE THREAD

**Issue by abernh** [itsrennyman/react-plock#28]
https://github.com/itsrennyman/react-plock/blob/e10bd852885d639f6d6e454d4e19ba10564260d1/packages/react-plock/src/Plock.tsx#L88

There is a ")" missing.
Not sure why it still works.

**Comment by itsrennyman** [comment]
Hello!

Thanks for the bug spot! Lucky for us the browser is smart enough!

By the way, the problem is now fixed in the latest version!

Enjoy!
